spring.application.name=BloodWave
spring.datasource.url=jdbc:postgresql://localhost:5481/BloodWave
spring.datasource.username=postgres
spring.datasource.password=123123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
jwt.secret-key = Q7f3pK9mZxL2R8VwA1cN6EJYH5U4B0dOeTgS+MFaXyI=
spring.mail.protocol=smtp
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

